// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Class1.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.Cloning.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Cloning.Recipes
{
    /// <summary>
    /// bug: DOCUMENTATION HERE.
    /// </summary>
#if !OBeautifulCodeCloningSolution
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.Cloning.Recipes", "See package version number")]
    internal
#else
    public
#endif
    class Class1
    {
    }
}